export const LIFESTYLE_EVIDENCE = [
  {
    id: "consistent-sleep",
    name: "Consistent sleep schedule",
    category: "Sleep & recovery",
    role: "Supports attention, memory consolidation, and stable daytime alertness",
    evidence_grade: "A",
    evidence_type: "Systematic reviews, controlled sleep studies, and longitudinal cohorts",
    studied_population: "Healthy adults and adults with irregular sleep schedules",
    effect_size: "Moderate, with larger benefits when correcting chronic sleep restriction or irregular timing",
    timeframe: "Several days for alertness; multiple weeks for stable circadian adaptation",
    limitations: "Effects vary with sleep need, shift work, illness, and baseline sleep debt",
    safety_info: "Persistent insomnia, breathing pauses, or severe daytime sleepiness warrant medical assessment",
    references: ["Watson et al., Sleep, 2015", "Phillips et al., Sci Rep, 2017"],
  },
  {
    id: "aerobic-exercise",
    name: "Regular aerobic exercise",
    category: "Movement",
    role: "Supports executive function, mood regulation, and long-term brain health",
    evidence_grade: "A",
    evidence_type: "Randomized trials, meta-analyses, and prospective cohort studies",
    studied_population: "Healthy adults, older adults, and previously inactive adults",
    effect_size: "Small-to-moderate improvements in executive function; strongest when moving from inactive to active",
    timeframe: "Acute mood and attention effects; cognitive changes generally emerge over 8–24 weeks",
    limitations: "Protocols, intensity, adherence, and measured outcomes vary substantially",
    safety_info: "Build intensity gradually and seek clinical guidance when exercise is medically restricted",
    references: ["Northey et al., Br J Sports Med, 2018", "Erickson et al., PNAS, 2011"],
  },
  {
    id: "mediterranean-pattern",
    name: "Mediterranean-style dietary pattern",
    category: "Nutrition",
    role: "Supports vascular health and may protect long-term cognitive function",
    evidence_grade: "B",
    evidence_type: "Randomized dietary trials and prospective cohort studies",
    studied_population: "Middle-aged and older adults, including people with cardiovascular risk",
    effect_size: "Small cognitive benefit over time; stronger evidence for cardiovascular risk reduction",
    timeframe: "Months to years rather than an acute performance effect",
    limitations: "Diet quality is difficult to isolate from socioeconomic and lifestyle factors",
    safety_info: "Individual allergies, metabolic conditions, and prescribed diets still apply",
    references: ["Valls-Pedret et al., JAMA Intern Med, 2015", "Loughrey et al., Adv Nutr, 2017"],
  },
  {
    id: "mindfulness",
    name: "Mindfulness practice",
    category: "Stress regulation",
    role: "May reduce perceived stress and improve attentional control",
    evidence_grade: "B",
    evidence_type: "Randomized trials and meta-analyses of structured mindfulness programs",
    studied_population: "Adults with elevated stress and mixed healthy populations",
    effect_size: "Small-to-moderate reduction in perceived stress; attention effects are smaller and variable",
    timeframe: "Typically 4–8 weeks of regular practice",
    limitations: "Blinding is difficult and program quality, adherence, and comparison groups vary",
    safety_info: "Not a substitute for mental-health treatment; intensive practice can be uncomfortable for some people",
    references: ["Goyal et al., JAMA Intern Med, 2014", "Creswell, Annu Rev Psychol, 2017"],
  },
];